# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Test, build and deploy ASP.NET Core app to Azure Web App - ExpenseTracker-DeanH

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Show selected SDK
        run: dotnet --version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Run automated tests
        run: dotnet test --configuration Release --no-build

      - name: Publish application
        run: dotnet publish ExpenseTracker/ExpenseTracker.csproj --configuration Release --no-build --output "${{ runner.temp }}/myapp"

      - name: Upload application artifact
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ runner.temp }}/myapp

  deploy:
    name: Deploy to Azure
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .\myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AEDB756A634840BCBA1F9BB74E3C4453 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B51C9CD6DE754624A0EA22D1FD62E828 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A2AED5D280C94543B91A9EA5A032F157 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ExpenseTracker-DeanH'
          slot-name: 'Production'
          package: .\myapp
