# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Test, build and deploy ASP.NET Core app to Azure Web App - ExpenseTracker-DeanH

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    name: Run tests
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore test dependencies
        run: dotnet restore .\ExpenseTracker.Tests\ExpenseTracker.Tests.csproj

      - name: Run tests
        run: dotnet test .\ExpenseTracker.Tests\ExpenseTracker.Tests.csproj --configuration Release --no-restore

  build:
    name: Build and publish
    runs-on: windows-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore application dependencies
        run: dotnet restore .\ExpenseTracker\ExpenseTracker.csproj

      - name: Build with dotnet
        run: dotnet build .\ExpenseTracker\ExpenseTracker.csproj --configuration Release --no-restore

      - name: Publish with dotnet
        run: dotnet publish .\ExpenseTracker\ExpenseTracker.csproj --configuration Release --no-build --output "${{ runner.temp }}\myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ runner.temp }}\myapp

  deploy:
    name: Deploy to Azure
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .\myapp

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_AEDB756A634840BCBA1F9BB74E3C4453 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B51C9CD6DE754624A0EA22D1FD62E828 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A2AED5D280C94543B91A9EA5A032F157 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ExpenseTracker-DeanH'
          slot-name: 'Production'
          package: .\myapp
